# Generated by Django 5.1.4 on 2025-05-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsP', '0004_post_banner_path_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
