# Generated by Django 5.1.4 on 2025-06-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsP', '0006_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(default='no-reply@example.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsP.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='No Subject', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_path',
            field=models.ImageField(upload_to='news_banners'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsP.category'),
        ),
    ]
